[Sun Dec 14 20:34:26 2014] [error] Internal Server Error: /api/jms/dashboard
[Sun Dec 14 20:34:26 2014] [error] Traceback (most recent call last):
[Sun Dec 14 20:34:26 2014] [error]   File "/srv/JMS/src/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_response
[Sun Dec 14 20:34:26 2014] [error]     response = middleware_method(request)
[Sun Dec 14 20:34:26 2014] [error]   File "/srv/JMS/src/venv/lib/python2.7/site-packages/django/middleware/common.py", line 72, in process_request
[Sun Dec 14 20:34:26 2014] [error]     if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
[Sun Dec 14 20:34:26 2014] [error]   File "/srv/JMS/src/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 619, in is_valid_path
[Sun Dec 14 20:34:26 2014] [error]     resolve(path, urlconf)
[Sun Dec 14 20:34:26 2014] [error]   File "/srv/JMS/src/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 494, in resolve
[Sun Dec 14 20:34:26 2014] [error]     return get_resolver(urlconf).resolve(path)
[Sun Dec 14 20:34:26 2014] [error]   File "/srv/JMS/src/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 343, in resolve
[Sun Dec 14 20:34:26 2014] [error]     for pattern in self.url_patterns:
[Sun Dec 14 20:34:26 2014] [error]   File "/srv/JMS/src/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
[Sun Dec 14 20:34:26 2014] [error]     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
[Sun Dec 14 20:34:26 2014] [error]   File "/srv/JMS/src/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
[Sun Dec 14 20:34:26 2014] [error]     self._urlconf_module = import_module(self.urlconf_name)
[Sun Dec 14 20:34:26 2014] [error]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Sun Dec 14 20:34:26 2014] [error]     __import__(name)
[Sun Dec 14 20:34:26 2014] [error]   File "/srv/JMS/src/JMS/urls.py", line 7, in <module>
[Sun Dec 14 20:34:26 2014] [error]     url(r'^api/jms/', include('job.urls')),
[Sun Dec 14 20:34:26 2014] [error]   File "/srv/JMS/src/venv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 28, in include
[Sun Dec 14 20:34:26 2014] [error]     urlconf_module = import_module(urlconf_module)
[Sun Dec 14 20:34:26 2014] [error]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Sun Dec 14 20:34:26 2014] [error]     __import__(name)
[Sun Dec 14 20:34:26 2014] [error]   File "/srv/JMS/src/job/urls.py", line 2, in <module>
[Sun Dec 14 20:34:26 2014] [error]     from job import views
[Sun Dec 14 20:34:26 2014] [error]   File "/srv/JMS/src/job/views.py", line 18, in <module>
[Sun Dec 14 20:34:26 2014] [error]     from job.JMS import JMS
[Sun Dec 14 20:34:26 2014] [error]   File "/srv/JMS/src/job/JMS.py", line 21
[Sun Dec 14 20:34:26 2014] [error]     self.users_dir = "%s/%s" % (self.base_dir "users/")
[Sun Dec 14 20:34:26 2014] [error]                                                      ^
[Sun Dec 14 20:34:26 2014] [error] SyntaxError: invalid syntax
[Sun Dec 14 20:34:31 2014] [error] Internal Server Error: /
[Sun Dec 14 20:34:31 2014] [error] Traceback (most recent call last):
[Sun Dec 14 20:34:31 2014] [error]   File "/srv/JMS/src/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
[Sun Dec 14 20:34:31 2014] [error]     resolver_match = resolver.resolve(request.path_info)
[Sun Dec 14 20:34:31 2014] [error]   File "/srv/JMS/src/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 343, in resolve
[Sun Dec 14 20:34:31 2014] [error]     for pattern in self.url_patterns:
[Sun Dec 14 20:34:31 2014] [error]   File "/srv/JMS/src/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
[Sun Dec 14 20:34:31 2014] [error]     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
[Sun Dec 14 20:34:31 2014] [error]   File "/srv/JMS/src/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
[Sun Dec 14 20:34:31 2014] [error]     self._urlconf_module = import_module(self.urlconf_name)
[Sun Dec 14 20:34:31 2014] [error]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Sun Dec 14 20:34:31 2014] [error]     __import__(name)
[Sun Dec 14 20:34:31 2014] [error]   File "/srv/JMS/src/JMS/urls.py", line 7, in <module>
[Sun Dec 14 20:34:31 2014] [error]     url(r'^api/jms/', include('job.urls')),
[Sun Dec 14 20:34:31 2014] [error]   File "/srv/JMS/src/venv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 28, in include
[Sun Dec 14 20:34:31 2014] [error]     urlconf_module = import_module(urlconf_module)
[Sun Dec 14 20:34:31 2014] [error]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Sun Dec 14 20:34:31 2014] [error]     __import__(name)
[Sun Dec 14 20:34:31 2014] [error]   File "/srv/JMS/src/job/urls.py", line 2, in <module>
[Sun Dec 14 20:34:31 2014] [error]     from job import views
[Sun Dec 14 20:34:31 2014] [error]   File "/srv/JMS/src/job/views.py", line 18, in <module>
[Sun Dec 14 20:34:31 2014] [error]     from job.JMS import JMS
[Sun Dec 14 20:34:31 2014] [error]   File "/srv/JMS/src/job/JMS.py", line 21
[Sun Dec 14 20:34:31 2014] [error]     self.users_dir = "%s/%s" % (self.base_dir "users/")
[Sun Dec 14 20:34:31 2014] [error]                                                      ^
[Sun Dec 14 20:34:31 2014] [error] SyntaxError: invalid syntax
